env:
  browser: true
  mocha: true
plugins:
  - mocha
  - react
parser: babel-eslint
parserOptions:
  sourceType: module
extends:
  - 'airbnb'
rules:
  comma-dangle: off
  arrow-body-style: off
  no-console: off
  no-alert: off
  import/no-unresolved: 0
  import/imports-first: 0
  import/newline-after-import: 0
  import/no-extraneous-dependencies: 0
  space-before-function-paren: 0
